# Generated by Django 3.2.9 on 2021-11-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_manager_app', '0002_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
