# Generated by Django 3.2.9 on 2021-11-17 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_manager_app', '0005_remove_skills_proficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.BooleanField(default=False)),
                ('char_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character_manager_app.character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character_manager_app.skills')),
            ],
        ),
    ]
