# Generated by Django 3.2.9 on 2021-11-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_manager_app', '0006_skillscharacter'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='proficiency',
            field=models.IntegerField(default=2),
        ),
    ]
