# Generated by Django 3.2.9 on 2021-11-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_manager_app', '0007_stats_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='armor_class',
            field=models.IntegerField(default=10),
        ),
    ]
