# Generated by Django 3.2.9 on 2021-11-17 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_manager_app', '0008_stats_armor_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.BooleanField(default=False)),
                ('char_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character_manager_app.character')),
                ('stats_points', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character_manager_app.statspoints')),
            ],
        ),
    ]
