# Generated by Django 3.2.9 on 2021-11-18 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_manager_app', '0009_statscharacter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('number_of_dice', models.SmallIntegerField(default=4)),
                ('dice_type', models.SmallIntegerField(default=8)),
                ('char_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character_manager_app.character')),
            ],
        ),
    ]
