# Generated by Django 3.2.9 on 2021-11-19 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_manager_app', '0010_weapons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('weight', models.SmallIntegerField(default=1)),
                ('description', models.TextField(default='')),
                ('char_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character_manager_app.character')),
            ],
        ),
    ]
